export enum EnumMenu {
  INITIAL = "INITIAL",
  SELECTSERVICE = "SELECTSERVICE",
  SELECTDATE = "SELECTDATE",
  SELECTHOUR = "SELECTHOUR",
  MYSERVICES = "MYSERVICES",
  SELECTREGISTER = "SELECTREGISTER",
}

export enum EnumStatus {
  APROVED = "aproved",
  REPROVED = "reproved",
  PENDENT = "pendent",
}
