name: Deploy to Firebase Hosting on merge
"on":
  push:
    tags:
      - "*"
      # "*" deploy pra tag
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AGENDAMENTO_C8DFA }}"
          channelId: live
          projectId: agendamento-c8dfa
